---
language: node_js
node_js:
  - "0.12"

sudo: required
dist: trusty

addons:
  code_climate:
    repo_token: 74740f388595590cab11e48b87581938d3596bf7718cd5df14ab90a8ab39e165
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g npm@^3"
  - "npm config set progress false"
  - "npm install phantomjs-prebuilt"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test

branches:
  only:
    - master
    - develop
